In [37]:
import numpy as np


In [45]:
x = np.ones((3, 3))

print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [44]:
y = np.zeros((3, 3))
print(y)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [42]:
x.dtype


dtype('float64')

In [46]:
y.dtype


dtype('float64')

In [48]:
#Create a 2D array "called w" as the following:
w = np.array([[11, 13, 15],[12, 14, 16]])
w
#np.arange(0, 10)
#np.arange(0, 10)

array([[11, 13, 15],
       [12, 14, 16]])

In [50]:
#Q#6: Create z array contains the numbers from 1 to 3.
z = np.array([[1, 2, 3]])
z

array([[1, 2, 3]])

In [ ]:
#Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".
w = np.array([[11, 13, 15],[12, 14, 16]])

z = np.array([[1, 2, 3]])

newArray = np.concatenate((w, z))

print(newArray)



#newArray = a.shape = (3, 4)

In [ ]:
#Q#8: Print all elements of "newArray" using the loop.
for newArray in a:
    print(newArray)

In [ ]:
#9: Reverse the columns and rows of "newArray".
newArray.ravel()

In [ ]:
#Q#10: Decrement all elements of "newArray" with 1.
newArray = np.arange(4)
newArray

In [ ]:
#Find smallest and biggest values in "newArray"
a.min

In [ ]:
#Print the first row of "newArray" using indexing.
newArray = np.arange()
newArray

In [ ]:
#Print the number equals 12 of "newArray" using indexing.
a[::12]

In [ ]:
#Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing
A[[0,13]]

In [ ]:
#Q#15: Change the shape of "newArray" to (9,1).
np.reshape(9, 1)

In [ ]:
#Q#16: Change the shape of "newArray" to (3,2).
